[project]
name = "agentdna-boilerplate"
version = "0.0.1"
requires-python = ">=3.10,<3.13"

dependencies = [
    "langchain>=1.0",
    "langgraph",
    "langchain-core",
    "langchain-mcp-adapters==0.3.2",
    "fastmcp",
    "httpx",
    "python-dotenv",
    "langchain-ollama",
    "langchain-google-genai",
    "langchain-openai",
]
