[project]
name = "agentdna-boilerplate"
version = "0.0.1"
requires-python = ">=3.10"

dependencies = [
    "langchain>=1.0",
    "langgraph",
    "langchain-core",
    "langchain-mcp-adapters",
    "fastmcp",
    "httpx",
    "python-dotenv",
    "questionary",
    "rich",
    "agent-dna",
    "cbac"
]

[project.optional-dependencies]
ollama = [
    "langchain-ollama",
]

gemini = [
    "langchain-google-genai",
]

openai = [
    "langchain-openai",
]

openai_compatible = [
    "langchain-openai",
]

all = [
    "langchain-ollama",
    "langchain-google-genai",
    "langchain-openai",
]